services:
  - type: web
    name: seguimiento-tareas-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: seguimiento-tareas-db
          property: connectionString

databases:
  - name: seguimiento-tareas-db
    databaseName: tareas_db
    user: tareas_user
